### ISSUE TITLE
Token request failed with error

### ISSUE THREAD

**Issue by yoelhor** [Azure-Samples/active-directory-b2c-android-native-msal#2]
Just download and run the app, getting following error message (I copied few lines before):

D/AuthenticationActivity: MSAL_LOG: MSAL 0.1.1 Android 25 [2017-05-12 04:47:37] ChromeCustomTab support is available, launching chrome tab.
I/BrowserTabActivity: MSAL 0.1.1 Android 25 [2017-05-12 04:48:40] BrowserTabActivity onCreate: received redirect from system webview.
D/BrowserTabActivity: MSAL_LOG: MSAL 0.1.1 Android 25 [2017-05-12 04:48:40] BrowserTabActivity onCreate: received redirect from system webview.
I/AuthenticationActivity: MSAL 0.1.1 Android 25 [2017-05-12 04:48:40] onNewIntent is called, received redirect from system webview.
D/AuthenticationActivity: MSAL_LOG: MSAL 0.1.1 Android 25 [2017-05-12 04:48:40] onNewIntent is called, received redirect from system webview.
I/AuthenticationActivity: MSAL 0.1.1 Android 25 [2017-05-12 04:48:40] Return to caller with resultCode: 2003; requestId: 198602100
D/AuthenticationActivity: MSAL_LOG: MSAL 0.1.1 Android 25 [2017-05-12 04:48:40] Return to caller with resultCode: 2003; requestId: 198602100
I/InteractiveRequest: MSAL 0.1.1 Android 25 [2017-05-12 04:48:41] Received request code is: 1001; result code is: 2003
D/InteractiveRequest: MSAL_LOG: MSAL 0.1.1 Android 25 [2017-05-12 04:48:41] Received request code is: 1001; result code is: 2003
I/AuthorizationResult: MSAL 0.1.1 Android 25 [2017-05-12 04:48:41] Auth code is successfully returned from webview redirect.
D/AuthorizationResult: MSAL_LOG: MSAL 0.1.1 Android 25 [2017-05-12 04:48:41] Auth code is successfully returned from webview redirect.
I/InteractiveRequest: MSAL 0.1.1 Android 25 [2017-05-12 04:48:41 - 1f1f9d68-67da-438a-8919-aeaf327c3d4b] Authorize request status is: SUCCESS
D/InteractiveRequest: MSAL_LOG: MSAL 0.1.1 Android 25 [2017-05-12 04:48:41 - 1f1f9d68-67da-438a-8919-aeaf327c3d4b] Authorize request status is: SUCCESS
V/HttpRequest: MSAL 0.1.1 Android 25 [2017-05-12 04:48:41 - 1f1f9d68-67da-438a-8919-aeaf327c3d4b] Sending Http Post request.
D/HttpRequest: MSAL_LOG: MSAL 0.1.1 Android 25 [2017-05-12 04:48:41 - 1f1f9d68-67da-438a-8919-aeaf327c3d4b] Sending Http Post request.
E/BaseRequest: MSAL 0.1.1 Android 25 [2017-05-12 04:48:42 - 1f1f9d68-67da-438a-8919-aeaf327c3d4b] **Token request failed with error: unexpected end of stream on Connection**{login.microsoftonline.com:443, proxy=DIRECT hostAddress=104.41.216.17 cipherSuite=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA protocol=http/1.1} (recycle count=0) java.io.IOException: unexpected end of stream on Connection{login.microsoftonline.com:443, proxy=DIRECT hostAddress=104.41.216.17 cipherSuite=TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA protocol=http/1.1} (recycle count=0)
                   at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:210)
                   at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
                   at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:906)
                   at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:782)
                   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463)
                   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
                   at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:243)
                   at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                   at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
                   at com.microsoft.identity.client.HttpRequest.executeHttpSend(HttpRequest.java:185)
                   at com.microsoft.identity.client.HttpRequest.sendWithRetry(HttpRequest.java:151)
                   at com.microsoft.identity.client.HttpRequest.send(HttpRequest.java:132)
                   at com.microsoft.identity.client.HttpRequest.sendPost(HttpRequest.java:109)
                   at com.microsoft.identity.client.Oauth2Client.executeHttpRequest(Oauth2Client.java:142)
                   at com.microsoft.identity.client.Oauth2Client.getToken(Oauth2Client.java:77)
                   at com.microsoft.identity.client.BaseRequest.performTokenRequest(BaseRequest.java:173)
                   at com.microsoft.identity.client.BaseRequest$1.run(BaseRequest.java:107)
                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                   at java.lang.Thread.run(Thread.java:761)
                Caused by: java.io.EOFException: \n not found: size=0 content=...
                   at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:200)
                   at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)

**Comment by parakhj** [comment]
@yoelhor did you get this issue resolved? Sorry about the late response.

**Comment by danieldobalian** [comment]
@yoelhor interested to hear if you resolved this. Looks like a network error based on the logs, but also could be a large response that used the entire buffer. 

The app successfully popper the system browser, signed in the end user, and received an auth code.  When it attempted to POST the auth code on the /token endpoint it failed.

**Comment by danieldobalian** [comment]
You have this error: `TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA` which indicates your client is using an HTTP cipher for TLS that's blacklisted by the standards community.  Read more in [RFC 7540](https://tools.ietf.org/html/rfc7540#section-9.2.2).
